server:
  port: 8003
spring:
#  config:
#    activate:
#      on-profile: dev
  application:
    name: EventService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_logger
    username: root
    password: root
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
---
spring:
  config:
    activate:
      on-profile: test
  server:
    port: 8003
  application:
    name: EventService
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  cloud:
    bus:
      enable: false
    consul:
      config:
        enable: false
      enable: false
      host: localhost
      port: 8500
      discovery:
        enable: false
        instance-id: ${spring.application.name}:${random.value}