server:
  port: 8003
spring:
#  config:
#    activate:
#      on-profile: dev
  application:
    name: EventService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.24:3306/projectLogger
    username: devroot
    password: root
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}