# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: "Reason for Build"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build Event Service with Maven
      run: mvn -B package --file EventService/pom.xml
    - name: Build User Service Service with Maven
      run: mvn -B package --file UserService/pom.xml
    - name: Build spring Gateway Service Service with Maven
      run: mvn -B package --file springCloudGatewayServer/pom.xml
    - name: Build Project Service Service with Maven
      run: mvn -B package --file projectLogger/ProjectService/pom.xml
      
